name: docker
on: []
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@v4
        with:
          overprovision-lvm: 'true'
          remove-dotnet: 'true'
          remove-android: 'true'
      - uses: actions/checkout@v3
      - uses: rlespinasse/github-slug-action@v4
      - uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REPO_DIR: "/home/Cropbox.jl"
          IMAGE_NAME: "cropbox/cropbox"
          LATEST_TAG_OFF: true
          ADDITIONAL_TAG: ${{ env.GITHUB_REF_SLUG }}
