name: test
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['1.8']
        os: [macos-latest, ubuntu-latest, windows-latest]
        arch: [x64]
        depwarn: [yes]
        include:
          - version: '1.7'
            os: macos-latest
            arch: x64
            depwarn: yes
          - version: '1.8'
            os: macos-latest
            arch: x64
            depwarn: error
          - version: 'nightly'
            os: macos-latest
            arch: x64
            depwarn: error
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: ""
      - uses: julia-actions/julia-runtest@v1
        with:
          depwarn: ${{ matrix.depwarn }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
